cc_binary(
    name = "zlib_usage_example",
    srcs = ["zlib_example.cpp"],
    deps = ["@zlib"],
)

cc_binary(
    name = "lz4_usage_example",
    srcs = ["lz4_frameCompress.c"],
    deps = ["@lz4"],
)
